name: OS-OCR Integrationstest
on:
  push:
    branches:
      - master
  workflow_call:
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: 'jadice-flow-postman-collection.json'
          environment: 'jadice-flow-postman-environment.json.json'
          folder: '["ocr-bundle"]'
          reporters: '["cli"]'
          envVar: '[{ "key": "JS_DIRECTOR_URL", "value": "https://ocr-jadice-flow.apps.openshift-05.matrix.de" }, { "key": "JADICE-SERVER-ACCESS-TOKEN", "value": "${{ secrets.JADICE_SERVER_ACCESS_TOKEN }}" }]'